package main.java.com.xfherun.jmci.user_interface.section.page_1;

public class AddAllPianoKeysStyle
{
    private AddAllPianoKeysStyle()
    {
    }

    public static void startB()
    {
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_0);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_1);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_2);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_3);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_4);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_5);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_6);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_7);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_8);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_9);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_10);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_11);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_12);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_13);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_14);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_15);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_16);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_17);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_18);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_19);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_20);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_21);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_22);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_23);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_24);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_25);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_26);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_27);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_28);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_29);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_30);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_31);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_32);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_33);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_34);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_35);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_36);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_37);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_38);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_39);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_40);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_41);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_42);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_43);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_44);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_45);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_46);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_47);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_48);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_49);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_50);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_51);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addBlackPianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_52);
    }

    public static void startW()
    {
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_0);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_1);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_2);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_3);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_4);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_5);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_6);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_7);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_8);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_9);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_10);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_11);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_12);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_13);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_14);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_15);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_16);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_17);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_18);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_19);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_20);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_21);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_22);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_23);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_24);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_25);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_26);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_27);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_28);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_29);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_30);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_31);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_32);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_33);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_34);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_35);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_36);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_37);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_38);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_39);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_40);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_41);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_42);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_43);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_44);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_45);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_46);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_47);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_48);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_49);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_50);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_51);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_52);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_53);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_54);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_55);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_56);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_57);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_58);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_59);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_60);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_61);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_62);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_63);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_64);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_65);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_66);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_67);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_68);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_69);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_70);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_71);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_72);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_73);
        SetWhitePianoKeysAndBlackPianoKeysStyle.addWhitePianoKeysStyle(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_74);
    }
}
