package main.java.com.xfherun.jmci.user_interface.section.page_1;

import main.java.com.xfherun.jmci.user_interface.section.MainContainerPage_1;

public class AddAllPianoKeysToContainer
{
    private AddAllPianoKeysToContainer()
    {
    }

    public static void addBlackPianoKeys()
    {
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_0);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_1);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_2);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_3);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_4);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_5);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_6);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_7);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_8);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_9);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_10);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_11);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_12);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_13);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_14);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_15);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_16);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_17);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_18);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_19);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_20);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_21);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_22);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_23);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_24);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_25);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_26);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_27);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_28);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_29);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_30);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_31);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_32);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_33);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_34);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_35);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_36);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_37);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_38);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_39);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_40);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_41);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_42);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_43);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_44);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_45);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_46);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_47);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_48);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_49);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_50);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_51);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.black_piano_key_item_index_52);
    }

    public static void addWhitePianoKeys()
    {
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_0);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_1);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_2);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_3);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_4);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_5);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_6);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_7);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_8);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_9);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_10);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_11);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_12);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_13);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_14);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_15);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_16);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_17);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_18);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_19);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_20);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_21);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_22);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_23);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_24);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_25);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_26);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_27);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_28);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_29);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_30);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_31);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_32);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_33);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_34);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_35);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_36);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_37);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_38);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_39);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_40);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_41);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_42);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_43);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_44);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_45);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_46);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_47);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_48);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_49);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_50);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_51);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_52);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_53);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_54);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_55);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_56);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_57);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_58);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_59);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_60);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_61);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_62);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_63);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_64);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_65);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_66);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_67);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_68);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_69);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_70);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_71);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_72);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_73);
        DrawPianoKeys.getKeyBox().add(WhitePianoKeysAndBlackPianoKeysObject.white_piano_key_item_index_74);
    }
}
